DROP TABLE IF EXISTS t_user;

CREATE TABLE t_user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  name VARCHAR(30) NOT NULL COMMENT '姓名',
  age INT(11) NULL DEFAULT NULL COMMENT '年龄',
  note VARCHAR(255) NULL DEFAULT NULL COMMENT '描述',
  PRIMARY KEY(id)
);
